name: Lint Codebase
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: master
          path: repo
          fetch-depth: 0
      - name: Run shellcheck
        run: docker run --rm -v "$PWD/repo:/mnt" koalaman/shellcheck:stable -a -f gcc -S style -o all "*.sh"
  shfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: master
          path: repo
          fetch-depth: 0
      - name: Run shfmt
        run: docker run --rm -v "$PWD/repo:/mnt" -w /mnt mvdan/shfmt:latest -d "*.sh"

